#!/bin/sh
# Spécifiez l'emplacement de votre exécutable `mysqldump`
# Si vous avez installé XAMPP à l'emplacement par défaut, cela pourrait ressembler à ceci:
MYSQLDUMP="C:/xampp/mysql/bin/mysqldump.exe"

#On récupère le nom de la base de données
DB_NAME=$(cat paramBDD.txt | grep "DB_NAME" | cut -d "=" -f 2)
#On récupère le nom de l'utilisateur
DB_USER=$(cat paramBDD.txt | grep "DB_USER" | cut -d "=" -f 2)
#On récupère le nom du fichier de dump par rapport au chemin du projet actuel
DUMP_FILE="./sql/$DB_NAME.sql"

"$MYSQLDUMP" -u $DB_USER $DB_NAME > $DUMP_FILE

# Ajoutez le dump à la liste des fichiers à commettre
git add $DUMP_FILE
 
exit 0